name: Create and publish the Synk.Encodings.Crockford Nuget package

on: 
    push: 
        tags: 
            - "v*"
env: 
    PROJECT_PATH: src/Synk.Encodings.Crockford/Synk.Encodings.Crockford
    PROJECT_NAME: Synk.Encodings.Crockford 
    PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}/src/Synk.Encodings.Crockford/bin/Release
    GITHUB_PACKAGE_SOURCE_URL: https://nuget.pkg.github.com/Sukup-Manufacturing-Company/index.json
jobs: 
    deploy:
        name: build-and-push-package 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v2

            - name: install dotnet 
              uses: actions/setup-dotnet@v1
              with: 
                 dotnet-version: '8.x.x' 
            
            - name: restore packages
              run: dotnet restore ${{env.PROJECT_PATH}}.csproj
            
            - name: build project 
              run: dotnet build ${{env.PROJECT_PATH}}.csproj --no-restore --configuration Release 
              
            - name: get version
              id: version
              uses: battila7/get-version-action@v2

            - name: pack project
              run: dotnet pack ${{env.PROJECT_PATH}}.csproj --no-restore --configuration Release --include-symbols -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}

            - name: auth to github packages
              run: dotnet nuget add source --username ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github ${{env.GITHUB_PACKAGE_SOURCE_URL}}
            
            - name: publish to github packages
              run: dotnet nuget push "src/Synk.Encodings.Crockford/bin/Release/${{env.PROJECT_NAME}}.${{steps.version.outputs.version-without-v}}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"